
spring:
  application.name: resulting

  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui
    operationsSorter: alpha

rabbitmq:
  queue: result-queue